apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-trigger-binding
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.url).git
    - name: git-repo-name
      value: $(body.repository.name)
    - name: git-revision
      value: main
