apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: git-revision
      description: The git revision
      default: 'main'
    - name: git-repo-name
      description: The name of the deployment to be created / patched
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: test-build-deploy-$(tt.params.git-repo-name)-$(uid)
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: test-build-deploy
        params:
          - name: deployment-name
            value: $(tt.params.git-repo-name)
          - name: git-url
            value: https://github.com/rhos-devadvo-br/pipelines-demo
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: IMAGE
            value: image-registry.openshift-image-registry.svc:5000/lab-pipelines/$(tt.params.git-repo-name)
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: tekton-pvc
